
domain: phlolu.github.io
baseurl: "/wtt-matchups" # the subpath of your site, e.g. /blog
url: "https://phlolu.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#Include
include:
  - _data/
  - _includes/
  - _layouts/
  - _sass/

