# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
#gem "jekyll"

# comment out gem jekyll above and use below when using github pages
gem "github-pages", "~> 228", group: :jekyll_plugins
